language: python

python:
  - "3.7"

jobs:
  include:
    - name: "Build Lab 2. Fail with tests"
      python: 3.7
      install:
        - cd ./lab2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - name: "Build Lab 3. Fail to run and test"
      python: 3.7
      install:
        - cd ./lab3/
        - pipenv install
      script: ./scripts/travis-build.sh
    - name: "Build Lab 4. Try to push images"
      services:
        - docker
      install:
        - cd ./lab4/
      script:
        - docker build -t bobas/lab4-examples:django .
        - docker images
    - name: "Build Lab 5. Success"
      services:
        - docker
      install:
        - cd ./lab5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
branches:
  only:
    - master