language: python

python:
  - "3.7"

jobs:
  include:
    - name: "Build Lab 2"
      python: 3.7
      install:
        - pip install pipenv
        - cd ./lab2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - name: "Build Lab 3"
      python: 3.7
      install:
        - cd ./lab3/
        - pipenv install
        - pipenv run server > ~/ci-build.log 2>&1 &
      script: pipenv run python monitoring.py
    - name: "Build Lab 4"
      services:
        - docker
      script:
        - cd ./lab4/
        - docker build -t bobas/lab4-examples:django .
        - docker images
branches:
  only:
    - master