language: python
python:
  - "3.7"
jobs:
  include:
    - name: "Test lab 2"
      python: 3.7
      install:
        - pip install pipenv
        - cd ./lab2/
        - pipenv install
      script: pipenv pytest tests/tests.py
branches:
  only:
    - master